spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3309/test?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: admin
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://127.0.0.1:3309/test2?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: admin
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver

  #color log
  output:
   ansi:
     enabled: always
  redis:
    database: 1
    host: 127.0.0.1
    port: 6376
    password: abc
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    #producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    #consumer
    consumer:
      group-id: qiqilab
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    com.qiqilab: DEBUG